mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('utilisateurs.urls')),
    path('programmes/', include('programmes.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

mysite/programmes/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import QuizView, QuizListView, QuizResultView
from . import views
from programmes.views import (
    LessonCreateView,
    LessonListViewDetail,
    LessonUpdateView,
    LessonDeleteView,
    LessonListView
)

app_name = "programmes"

urlpatterns = [
    path('create/', LessonCreateView.as_view(), name="lessoncreate"),
    path('lessonlist/', LessonListView.as_view(), name='lessonlist'),
    path('lessonlist/<slug:slug>/', LessonListViewDetail.as_view(), name='lessonlistslug'),
    path('<slug:slug>/update', LessonUpdateView.as_view(), name="lessonupdate"),
    path('<slug:slug>/delete', LessonDeleteView.as_view(), name="lessondelete"),
    path('quiz/<int:pk>/', QuizView.as_view(), name='quiz_view'),
    path('quiz_list/<slug:slug>/', QuizListView.as_view(), name='quiz_list'),
    path('quiz_result/', QuizResultView.as_view(), name='quiz_result'),
    path('<slug:slug>/', LessonListViewDetail.as_view(), name="lessonlistdetail"),
    path('lessons/<slug:slug>/download_pdf/', views.download_lesson_pdf, name='download_lesson_pdf')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/programmes/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from django.urls import reverse

class Lesson(models.Model):# represente une leçon et ses differents attributs dans la base du donnée
    lesson_id = models.AutoField(primary_key=True)
    creer_par = models.ForeignKey(User, on_delete=models.CASCADE)
    nom = models.CharField(max_length=100)
    slug = models.SlugField(blank=True, null=True)
    position = models.PositiveSmallIntegerField(verbose_name='chapitre no')
    video = models.FileField(upload_to="Video", null=True, blank=True, verbose_name="cours en video")
    fpe = models.FileField(upload_to="FPE", null=True, blank=True, verbose_name="Fichier en presentation")
    pdf = models.FileField(upload_to="PDF", null=True, blank=True, verbose_name="cours en PDF")

    class Meta:
        ordering = ['position']

    def __str__(self):
        return self.nom

    def save(self, *args, **kwargs):
        self.slug = slugify(self.nom)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("programmes:lessonlist", kwargs={"slug": self.slug})

class Commentaire(models.Model):# represente un commentaire sur un leçon
    nom_lesson = models.ForeignKey(Lesson, null=True, on_delete=models.CASCADE, related_name='comments')
    nom_comm = models.CharField(max_length=100, blank=True)
    auteur = models.ForeignKey(User, on_delete=models.CASCADE)
    corps = models.TextField(max_length=500)
    date_added = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        self.nom_comm = slugify("commente par " + str(self.auteur) + " a " + str(self.date_added))
        super().save(*args, **kwargs)

    def __str__(self):
        return self.nom_comm
    
    class Meta:
        ordering = ['-date_added']

class Reponse(models.Model):
    nom_comm = models.ForeignKey(Commentaire, on_delete=models.CASCADE, related_name='reponses')
    corps = models.TextField(max_length=500)
    auteur = models.ForeignKey(User, on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "reponse a " + str(self.nom_comm.nom_comm)
    
class Quiz(models.Model):
    name = models.CharField(max_length=200)
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)
    score = models.IntegerField(default=0)

class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    answer = models.CharField(max_length=200, blank=True, null=True)  # Autoriser les valeurs nulles


class Option(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    is_correct = models.BooleanField(default=False)

mysite/programmes/forms.py
from django import forms
from .models import Lesson, Commentaire, Reponse

class LessonForm(forms.ModelForm):
    class Meta:
        model = Lesson
        fields = ('lesson_id', 'nom', 'video', 'fpe', 'pdf', 'position')

    
class ComForm(forms.ModelForm):
    class Meta:
        model = Commentaire
        fields = ('corps',)
        lables = {'corps': 'Commentaire'}
        widgets = {
            'corps':forms.Textarea(attrs={
                'class': 'form-control',
                'rows': 4,
                'cols':70,
                'placeholder':'Entrez votre commentaire ici.'
            })
        }


class RepForm(forms.ModelForm):
    class Meta:
        model = Reponse
        fields = ('corps',)
        lables = {'corps': 'Reponses'}
        widgets = {
            'corps':forms.Textarea(attrs={
                'class': 'form-control',
                'rows': 2,
                'cols':10,
                'placeholder':'Repondez ici.'
            })
        }

mysite/programmes/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import DetailView, CreateView, UpdateView, DeleteView, FormView, ListView
from django.urls import reverse_lazy
from .models import Lesson, Quiz, Question, Option
from .forms import LessonForm, ComForm, RepForm
from django.http import HttpResponseRedirect, FileResponse
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.decorators import login_required

class LessonListView(ListView):# vue utilise toutes leçons dans le template (lessonlist.html)
    model = Lesson
    template_name = 'programmes/lessonlist.html'
    context_object_name = 'lessons'
    def get_queryset(self):
        return Lesson.objects.all()

class LessonListViewDetail(DetailView, FormView):#affiche les details d une leçon dans template (lessonlistdetail.htm)
    context_object_name = 'lesson'
    model = Lesson
    template_name = 'programmes/lessonlistdetail.html'
    form_class = ComForm
    second_form_class = RepForm

    def get_context_data(self, **kwargs):
        context = super(LessonListViewDetail, self).get_context_data(**kwargs)

        if 'form' not in context:
            context['form'] = self.form_class()
        if 'form2' not in context:
            context['form2'] = self.second_form_class()

        context['quizzes'] = Quiz.objects.filter(lesson=self.object)

        return context

    def form_valid(self, form):
        self.object = self.get_object()
        fd = form.save(commit=False)
        fd.auteur = self.request.user
        fd.nom_lesson_id = self.object.pk
        fd.save()
        return HttpResponseRedirect(self.get_success_url())

    def form_valid2(self, form):
        self.object = self.get_object()
        fd = form.save(commit=False)
        fd.auteur = self.request.user
        fd.nom_comm_id = self.request.POST.get('comment_id')
        fd.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse_lazy('programmes:lessonlistdetail', kwargs={'slug': self.object.slug})

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        if 'form2' in request.POST:
            form_class = self.second_form_class
            form_name = 'form2'
        else:
            form_class = self.form_class
            form_name = 'form'
        
        form = form_class(request.POST)

        if form_name == 'form' and form.is_valid():
            return self.form_valid(form)

        if form_name == 'form2' and form.is_valid():
            return self.form_valid2(form)
        
        return self.render_to_response(self.get_context_data(form=form))

class LessonCreateView(UserPassesTestMixin, CreateView):
    form_class = LessonForm
    model = Lesson
    template_name = 'programmes/lessoncreate.html'

    def get_success_url(self):
        return reverse_lazy('programmes:lessonlistslug', kwargs={'slug': self.object.slug})

    def form_valid(self, form, *args, **kwargs):
        self.object = form.save(commit=False)
        self.object.creer_par = self.request.user
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def test_func(self):
        return self.request.user.is_staff or self.request.user.groups.filter(name='ENSEIGNANT').exists()


    

class LessonUpdateView(UpdateView):
    fields = ('nom', 'position', 'pdf', 'fpe')
    context_object_name = 'lesson'
    model = Lesson
    template_name = 'programmes/lessonupdate.html'

    def get_success_url(self):
        return reverse_lazy("programmes:lessonlist")

class LessonDeleteView(DeleteView):
    model = Lesson
    context_object_name = "lesson"
    template_name = 'programmes/lessondelete.html'

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        request.session['slug'] = self.object.slug
        return super().delete(request, *args, **kwargs)

    def get_success_url(self):
        return reverse_lazy("programmes:lessonlist")
    
class QuizView(DetailView):
    model = Quiz
    template_name = 'programmes/quiz.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['questions'] = Question.objects.filter(quiz=self.object).prefetch_related('option_set')
        return context
    
    def post(self, request, *args, **kwargs):
        quiz = self.get_object()
        questions = quiz.question_set.all()
        score = 0
        
        for question in questions:
            selected_option_id = request.POST.get(f'question_{question.id}')
            if selected_option_id:
                selected_option = get_object_or_404(Option, id=selected_option_id)
                if selected_option.is_correct:
                    score += 1

        # Store the score in the session
        request.session['score'] = request.session.get('score', 0) + score
        
        # Get the next quiz in the same lesson
        next_quiz = Quiz.objects.filter(lesson=quiz.lesson, id__gt=quiz.id).first()
        
        if next_quiz:
            return redirect('programmes:quiz_view', pk=next_quiz.id)
        else:
            return redirect('programmes:quiz_result')



class QuizResultView(DetailView):
    template_name = 'programmes/quiz_result.html'
    
    def get(self, request, *args, **kwargs):
        score = request.session.get('score', 0)
        del request.session['score']
        return render(request, self.template_name, {'score': score})
    
    

def quiz_view(request, quiz_id):
    quiz = Quiz.objects.get(id=quiz_id)
    questions = quiz.question_set.all()
    return render(request, 'quiz.html', {'quiz': quiz, 'questions': questions})

class QuizDetailView(DetailView):
    model = Quiz
    template_name = 'programmes/quiz_detail.html'
    context_object_name = 'quiz'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['questions'] = self.object.question_set.all()
        return context
    
    def get_queryset(self):
        return Quiz.objects.filter(lesson__slug=self.kwargs['slug'])
    
class QuizListView(ListView):
    model = Quiz
    template_name = 'quiz_list.html'
    context_object_name = 'quizzes'

    def get_queryset(self):
        # Récupérer la leçon associée à l'URL
        lesson_slug = self.kwargs['slug']
        lesson = get_object_or_404(Lesson, slug=lesson_slug)
        
        # Filtrer les quiz associés à la leçon
        return Quiz.objects.filter(lesson=lesson)
    
    
def lesson_detail(request, lesson_id):
    # Récupérer la leçon actuelle
    lesson = get_object_or_404(Lesson, pk=lesson_id)
    # Filtrer les quiz associés à la leçon actuelle
    quizzes = Quiz.objects.filter(lesson=lesson)

    context = {
        'lesson': lesson,
        'quizzes': quizzes,
    }

    return render(request, 'lesson_detail.html', context)

def download_lesson_pdf(request, slug):
    lesson = get_object_or_404(Lesson, slug=slug)
    return FileResponse(open(lesson.pdf.path, 'rb'), content_type='application/pdf')

mysite/programmes/templates/programmes/lessoncreate.html
{% extends 'base.html' %}

{% block content %}
<style>
    body {
        font-family: 'Roboto', sans-serif;
        background: linear-gradient(to right, #000, #006400);
        color: #333;
        margin: 0;
        padding: 0;
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
    }

    .form-container {
        background: rgba(255, 255, 255, 0.9);
        padding: 40px;
        border-radius: 15px;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.2);
        backdrop-filter: blur(10px);
        max-width: 600px;
        width: 100%;
        text-align: center;
    }

    form {
        display: flex;
        flex-direction: column;
        align-items: center;
    }

    form input[type="text"],
    form input[type="password"],
    form input[type="email"],
    form select,
    form textarea {
        width: 100%;
        padding: 12px;
        margin: 10px 0;
        border: 1px solid #ddd;
        border-radius: 5px;
        box-shadow: 0 5px 10px rgba(0, 0, 0, 0.1);
        font-size: 16px;
    }

    form input[type="submit"] {
        background-color: #000;
        color: white;
        border: none;
        padding: 15px 20px;
        font-size: 16px;
        font-weight: bold;
        border-radius: 30px;
        cursor: pointer;
        transition: background-color 0.3s ease, transform 0.2s ease;
        text-transform: uppercase;
        margin-top: 20px;
        text-shadow: 0 0 5px rgba(255, 255, 255, 0.6);
    }

    form input[type="submit"]:hover {
        background-color: #333;
        transform: scale(1.05);
    }

    form input[type="submit"]:focus {
        outline: none;
    }
</style>

<div class="form-container">
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Confirmer la création">
    </form>
</div>
{% endblock %}

mysite/programmes/templates/programmes/lessondelete.html
{% extends 'base.html' %}

{% block content %}
<h1> Etes vous sure de vouloir supprimer ? </h1>
<form method="POST">
{% csrf_token %}
<input type="submit" value="Supprimer definitivement " >
<a href="{% url 'programmes:lessonlistdetail' slug=lesson.slug %}">annuler la suppression </a></form>

{% endblock %}

mysite/programmes/templates/programmes/lessonlist.html
{% extends 'base.html' %}

{% block content %}
<style>
    .lesson-item {
        width: calc(33.33% - 20px); /* Largeur de chaque élément (1/3 de la largeur de la ligne) */
        margin: 10px; /* Marge autour de chaque élément */
        display: inline-block;
        text-align: center;
        position: relative; /* Positionnement relatif pour positionner les stickers */
        background: linear-gradient(135deg, #f0f0f0 0%, #e6e6e6 100%); /* Effet de gradient */
        border-radius: 10px; /* Coins arrondis */
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); /* Ombre portée */
        transition: transform 0.2s, box-shadow 0.2s, background-color 0.5s; /* Transition pour les effets de survol */
    }

    .lesson-item:hover {
        transform: translateY(-5px); /* Déplacer légèrement l'élément vers le haut au survol */
        box-shadow: 0 8px 16px rgba(0, 0, 0, 0.2); /* Augmenter l'ombre portée au survol */
        animation: float 5s ease-in-out infinite; /* Effet de 'flottement' au survol */
    }

    @keyframes float {
        0%, 100% {
            transform: translateY(0);
        }
        50% {
            transform: translateY(-10px);
        }
    }

    .lesson-name {
        margin-top: 40px; /* Marge en haut du nom de la leçon, ajustée pour l'espace du sticker */
        font-weight: bold; /* Texte en gras */
        color: #333; /* Couleur du texte */
    }

    .lessons-container {
        display: flex; /* Utilisation d'un conteneur flex pour organiser les éléments */
        flex-wrap: wrap; /* Permettre le passage à la ligne lorsque nécessaire */
        justify-content: space-between; /* Espacement égal entre les éléments */
    }

    .lesson-teacher {
        background-color: #007bff; /* Bleu pour les enseignants */
    }

    .lesson-student {
        background-color: #ffc107; /* Jaune pour les étudiants */
    }

    .lesson-teacher:hover {
        background-color: #009bff; /* Bleu plus clair au survol pour les enseignants */
    }

    .lesson-student:hover {
        background-color: #ffca28; /* Jaune plus clair au survol pour les étudiants */
    }

    .btn-creative {
        background-color: #4caf50; /* Couleur de fond verte */
        border: none; /* Pas de bordure */
        color: white; /* Texte blanc */
        padding: 15px 32px; /* Padding */
        text-align: center; /* Alignement du texte */
        text-decoration: none; /* Pas de soulignement */
        display: inline-block; /* Affichage en ligne */
        font-size: 16px; /* Taille de la police */
        margin: 20px 2px; /* Marge */
        cursor: pointer; /* Curseur pointer */
        border-radius: 12px; /* Bords arrondis */
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); /* Ombre portée */
        transition: background-color 0.3s, transform 0.3s; /* Transition pour le survol */
    }

    .btn-creative:hover {
        background-color: #45a049; /* Couleur de fond plus sombre au survol */
        transform: scale(1.05); /* Agrandissement léger au survol */
    }

    .btn-creative:active {
        transform: scale(0.95); /* Réduction légère au clic */
    }
</style>

<div class="lessons-container">
    {% for lesson in lessons %}
    <div class="lesson-item {% if lesson.teacher %}lesson-teacher{% elif lesson.student %}lesson-student{% endif %}">
        <a href="{% url 'programmes:lessonlistdetail' slug=lesson.slug %}">
            <div class="lesson-name">Chapitre-{{ lesson.position }} {{ lesson.nom }}</div>
        </a>
    </div>
    {% endfor %}
</div>

{% if user.is_superuser or user.profile.type_profil == 'enseignant' %}
#pour afficher le formulaire de création de leçon seulement aux tuteurs ou admin
<a href="{% url 'programmes:lessoncreate' %}" class="btn btn-creative">Créer une leçon</a>
{% endif %}
{% endblock %}

mysite/programmes/templates/programmes/lessonlistdetail.html
{% extends 'base.html' %}

{% block content %}

<style>
    body {
        font-family: 'Roboto', sans-serif;
        line-height: 1.6;
        margin: 0;
        padding: 0;
        background: radial-gradient(circle, rgba(144,238,144,1) 0%, rgba(34,139,34,1) 100%);
        color: #333;
        transition: background-color 0.5s ease;
    }

    .container {
        padding: 20px;
        background: rgba(255, 255, 255, 0.9);
        border-radius: 15px;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.2);
        backdrop-filter: blur(10px);
        max-width: 1200px;
        margin: 20px auto;
        animation: fadeIn 1s ease-in-out;
    }

    @keyframes fadeIn {
        from { opacity: 0; }
        to { opacity: 1; }
    }

    .lesson-details {
        background-color: rgba(255, 255, 255, 0.8);
        border: 1px solid #ddd;
        padding: 20px;
        border-radius: 10px;
        margin-bottom: 20px;
        box-shadow: 0 5px 15px rgba(0, 0, 0, 0.1);
        transition: transform 0.3s ease, box-shadow 0.3s ease;
    }

    .lesson-details:hover {
        transform: scale(1.02);
        box-shadow: 0 10px 30px rgba(0, 0, 0, 0.2);
    }

    .lesson-details p {
        margin: 10px 0;
        color: #333;
    }

    a {
        color: #1e90ff;
        text-decoration: none;
        font-weight: bold;
    }

    a:hover {
        text-decoration: underline;
    }

    .btn {
        display: inline-block;
        padding: 12px 25px;
        font-size: 14px;
        font-weight: bold;
        border-radius: 30px;
        text-align: center;
        cursor: pointer;
        margin-top: 10px;
        transition: background-color 0.3s ease, transform 0.2s ease;
        text-transform: uppercase;
    }

    .btn-primary {
        background-color: #1e90ff;
        color: white;
        border: none;
    }

    .btn-primary:hover {
        background-color: #1c86ee;
        transform: scale(1.05);
    }

    .btn-warning {
        background-color: #ff8c00;
        color: white;
        border: none;
    }

    .btn-warning:hover {
        background-color: #ee7600;
        transform: scale(1.05);
    }

    .btn-success {
        background-color: #32cd32;
        color: white;
        border: none;
    }

    .btn-success:hover {
        background-color: #2eb82e;
        transform: scale(1.05);
    }

    .comment-section {
        margin-top: 40px;
    }

    .comment-section h4 {
        margin-bottom: 20px;
        color: #333;
        font-weight: bold;
    }

    .comment-form,
    .reply-form {
        margin-bottom: 20px;
        background-color: rgba(255, 255, 255, 0.8);
        padding: 20px;
        border-radius: 10px;
        border: 1px solid #ddd;
        box-shadow: 0 5px 10px rgba(0, 0, 0, 0.1);
    }

    .form-group {
        margin-bottom: 20px;
    }

    .comment {
        background-color: rgba(255, 255, 255, 0.9);
        padding: 15px;
        border-radius: 10px;
        margin-bottom: 20px;
        border: 1px solid #ddd;
        box-shadow: 0 5px 10px rgba(0, 0, 0, 0.1);
        transition: transform 0.3s ease, box-shadow 0.3s ease;
    }

    .comment:hover {
        transform: scale(1.02);
        box-shadow: 0 10px 30px rgba(0, 0, 0, 0.2);
    }

    .comment h4 {
        margin-top: 0;
        color: #333;
    }

    .comment small {
        color: #555;
    }

    .reply {
        background-color: rgba(240, 255, 240, 0.9);
        padding: 10px;
        border-radius: 10px;
        margin-left: 20px;
        margin-bottom: 10px;
        border: 1px solid #ccc;
        box-shadow: 0 5px 10px rgba(0, 0, 0, 0.1);
        transition: transform 0.3s ease, box-shadow 0.3s ease;
    }

    .reply:hover {
        transform: scale(1.02);
        box-shadow: 0 10px 30px rgba(0, 0, 0, 0.2);
    }
</style>

<div class="container">

    <div class="lesson-details">
        <p>La leçon intitulée {{ lesson.nom }} a été créée par {{ lesson.creer_par }}</p><br>
        <p>{{ lesson.description }}</p><br>

        {% if lesson.video %}
            <a href="{{ lesson.video.url }}" target="_blank" class="btn btn-primary">Ouvrir la vidéo</a>
        {% else %}
            <p>Aucune vidéo n'a été téléchargée pour cette leçon.</p>
        {% endif %}

        {% if lesson.fpe %}
            <a href="{{ lesson.fpe.url }}" target="_blank" class="btn btn-primary">Ouvrir le fichier de présentation</a><br>
        {% else %}
            <p>Aucun fichier de présentation n'a été téléchargé pour cette leçon.</p>
        {% endif %}

        {% if lesson.pdf %}
            <a href="{{ lesson.pdf.url }}" target="_blank" class="btn btn-primary">Ouvrir le cours en PDF</a><br>
        {% else %}
            <p>Aucun cours en PDF n'a été téléchargé pour cette leçon.</p>
        {% endif %}

        {% if user.is_superuser or user.profile.type_profil == 'enseignant' %}
            <a href="{% url 'programmes:lessonupdate' slug=lesson.slug %}" class="btn btn-warning">Modifier la leçon</a><br>
            <a href="{% url 'programmes:lessondelete' slug=lesson.slug %}" class="btn btn-warning">Supprimer la leçon</a><br>
        {% endif %}
        
    </div>

    <div class="comment-section">
        <h4>Postez votre commentaire ici bas.</h4>

        <form method="post" class="comment-form">
            {% csrf_token %}
            <div class="form-group">
                {{ form.as_p }}
                <input type="submit" name="form" value="Ajouter un commentaire" class="btn btn-success btn-sm">
            </div>
        </form>

        {% for comment in lesson.comment.all %}
            <div class="comment">
                <h4>{{ comment.auteur }} <small><i>poste le {{ comment.date_added }}</i></small></h4>
                <p>{{ comment.corps }}</p>

                {% for reponse in comment.reponses.all %}
                    <div class="reply">
                        <h5>{{ reponse.auteur }} <small><i>poste le {{ reponse.date_added }}</i></small></h5>
                        <p>{{ reponse.corps }}</p>
                    </div>
                {% endfor %}

                <form method="POST" class="reply-form">
                    {% csrf_token %}
                    <input type="hidden" name="comment_id" value="{{ comment.id }}">
                    {{ form2.as_p }}
                    <input type="submit" name="form2" value="Répondez" class="btn btn-primary btn-sm">
                </form>
            </div>
        {% endfor %}
    </div>

    <a href="{% url 'programmes:quiz_list' slug=lesson.slug %}" class="btn btn-primary">Allez au quiz</a>
</div>
{% endblock %}

mysite/programmes/templates/programmes/lessonupdate.html
{% extends 'base.html' %}

{% block content %}
<style>
    body {
        font-family: 'Roboto', sans-serif;
        background: linear-gradient(135deg, #a8c0ff 0%, #f0f2f0 100%);
        margin: 0;
        padding: 0;
        display: flex;
        flex-direction: column;
        align-items: center;
        min-height: 100vh;
        color: #333;
    }

    form {
        background: #fff;
        border-radius: 8px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        margin: 20px;
        padding: 20px;
        width: 80%;
        max-width: 500px;
        display: flex;
        flex-direction: column;
        gap: 10px;
    }

    form input[type="submit"] {
        background-color: #4caf50; /* couleur du bouton */
        color: white; /* couleur du texte */
        border: none;
        border-radius: 8px;
        padding: 10px;
        cursor: pointer;
        transition: background-color 0.3s;
    }

    form input[type="submit"]:hover {
        background-color: #45a049; /* couleur du bouton au survol */
    }

    form a {
        text-decoration: none;
        color: #f44336; /* couleur du lien */
        font-size: 16px;
        text-align: center;
        margin-top: 10px;
        display: block;
        transition: color 0.3s;
    }

    form a:hover {
        color: #c62828; /* couleur du lien au survol */
    }
</style>

<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Confirmer la modification">
    <a href="{% url 'programmes:lessonlistdetail' slug=lesson.slug %}">Annuler la modification</a>
</form>
{% endblock %}

mysite/programmes/templates/programmes/quiz_result.html
<!DOCTYPE html>
<html>
<head>
    <title>Résultat du Quiz</title>
    <style>
        body {
            font-family: 'Roboto', sans-serif;
            background: linear-gradient(to right, #ffecd2 0%, #fcb69f 100%);
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .container {
            max-width: 800px;
            margin: 50px auto;
            padding: 20px;
            background: rgba(255, 255, 255, 0.8);
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.2);
            border-radius: 15px;
            backdrop-filter: blur(10px);
        }

        h1 {
            text-align: center;
            color: #333;
            font-size: 2.5em;
            margin-bottom: 20px;
            text-transform: uppercase;
            letter-spacing: 2px;
        }

        .message {
            margin-top: 30px;
            padding: 20px;
            background-color: #ffd966;
            border-radius: 8px;
            border: 1px solid #e6b800;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Votre score: {{ score }}</h1>
        <a href="{% url 'acceuil' %}">Retour à l'accueil</a>
        <div class="message">
            <p style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; color: #333;">
                Si votre score est inférieur à 5, nous vous recommandons de revoir votre cours et refaire le quiz ultérieurement.
            </p>
        </div>
    </div>
</body>
</html>